### ISSUE TITLE
Error when using with webpack

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/Visualizations#9]
Uncaught Error: Cannot find module "./chart"
    at webpackMissingModule (atlascharts.js:3587)
    at Object.<anonymous> (atlascharts.js:3587)
    at Object.<anonymous> (atlascharts.js:3611)
    at Object.defineProperty.value (atlascharts.js:3613)
    at __webpack_require__ (

**Comment by chrisknoll** [comment]
The module IDs in the visualization library uses relative module path. It looks like you are using the rjs optimized file in your code (because of atlascharts.js) and I'm thinking you should probably go with the mdoe of doing npm install @ohdsi/atlascharts and reference the local node_modules path to package the library for your own app.  Otherwise, you'll need specific configuration options in your webpack setting to resolve those paths.

Something here might help you:
https://gist.github.com/xjamundx/b1c800e9282e16a6a18e

**Comment by pavgra** [comment]
@chrisknoll, this is nearly first time we face problems with webpack's module resolution. Although we can solve it using webpack custom config or in some other way, it feels like the problem is in the module. When you install smth from npm, you should not think of how to cook it, just require. Could you explain, why it is not suitable to enable possibility for webpack users to require this module without hacking by bringing in such modifications? (Which we already implemented and just suggest to accept)

**Comment by pavgra** [comment]
@chrisknoll, also, speaking of `npm install`, what you'll find in practically every tutorial, is to _exclude_ node modules from babel processing. So you relatives requires (same as requires at all) are not going to work inside of node_modules (and this is how it is typically done).

Anyway, for us to suggest better code and solutions, could you describe why our solution is not acceptable? It is not breaking anything and it allows to use module with webpack out-of-the-box, sp what is wrong, what can we improve?

**Comment by chrisknoll** [comment]
I saw the modifications, but they are not acceptable because you don't want to use absolute module IDs for submodules.  I'm sorry that this is the first time you've had this problem, but what have you done with relative module IDs in the past?

I think for webpack purposes, you should npm install it, and you shouldn't have to think about how to cook it.  It should work like any other npm module you install.  The thing is you are using the already bundled module (atlascharts.js) when in your case (using webpack) you should npm install and reference the module as if the entry (main.js) is found here:
/node_modules/@ohdsi/atlascharts/atlascharts/main.js

I'm pretty sure this is standard practice when installing modules from NPM and using webpack...

I understand you think you solved this by making all moduleIDs absolute pathed, but that's not correct, and is more of a 'hack' then having to get the proper webpack configuration.

**Comment by chrisknoll** [comment]
> Anyway, for us to suggest better code and solutions, could you describe why our solution is not acceptable? It is not breaking anything and it allows to use module with webpack out-of-the-box, sp what is wrong, what can we improve?

I've already explained:  the change you are making by removing relative module IDs forces everyone to create module paths to each individual module in the package.  You shouldn't need to do that, you should just specify a root path to the module and all the relative modules resolve based off the module root.

**Comment by chrisknoll** [comment]
@pavgra how would you leverage a library like d3?  They use relative paths all over:

**Comment by pavgra** [comment]
@chrisknoll, if I'm using something from NPM, I used not to think of how it was coded, what were the require-s, type of paths, etc, because one of NPMs ideas, as I see it, is to provide compiled (transpiled or however call it) and ready-to-use-everywhere bundle, which exports something and that's it.

So returning back to d3, you can go to `node_modules\d3-array` and there find a `package.json`. Inside it there is a property `main` which holds `build/d3-array.js`. So it targets not the src, but compiled version of code, which just exposes things I need. And I do not think of any webpack customization, exactly as with all other libs.

**Comment by chrisknoll** [comment]
Then it sounds like the path forward is to add a new build step to the Visualizations package.json that produces a webpack-ready library (and maybe it's more than webpack, it supports just global inclusion via scirpt tags) and then we can reference it that way. If you'd like to claim the moniker of atlascharts.min.js and atlascharts.js because you might argure that it's more globally compatable (whiel the current atlascharts.js expects an AMD context), that's fine and we can rename the currnt output from the require.js build to atlascharts.amd.js and atlascharts.amd.min.js.

**Comment by pavgra** [comment]
@chrisknoll, cool, that we found a way to manage it! Then I would propose following:
- add build process which produces UMD module;
- add a link to that JS file into `package.json` in a same way which I mentioned above.

Will it work for you?

**Comment by chrisknoll** [comment]
> add build process which produces UMD module;
That works, can you take that on?

>add a link to that JS file into package.json in a same way which I mentioned above.
I don't see where you talked about a link to the js file in package.json, but if it doesn't disrupt the current functionality with respect to the amd build (ie: we can still find the amd optimized file in /dist/atlascharts.amd.js for example) then I'm also fine with the proposal.

You may need to revert the changes you made to your master branch in your fork...

**Comment by chrisknoll** [comment]
@pavgra , sorry I found it: inside package.json there's a 'main' property that points to /dist/atlascharts.js.  If you build a UMD and want to point the main property to that, that works for me as well.

Let me know if there's anything you need on my end.
